# Generated by Django 2.2.4 on 2019-08-30 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fcuser',
            new_name='swuser',
        ),
    ]
