# Generated by Django 2.2.4 on 2019-09-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0002_auto_20190830_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='swuser',
            options={'verbose_name': '성우 고객', 'verbose_name_plural': '성우 고객'},
        ),
        migrations.AddField(
            model_name='swuser',
            name='useremail',
            field=models.EmailField(default='swpheus@gmail.com', max_length=128, verbose_name='사용자이메일'),
            preserve_default=False,
        ),
    ]
