# Generated by Django 2.2.4 on 2019-09-07 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0003_auto_20190906_1600'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='swuser',
            new_name='Fcuser',
        ),
    ]
